#ifndef CONFIG_H
#define CONFIG_H

#define MAX_MATERIAS_POR_ALUMNO 10
#define MAX_ALUMNOS_POR_MATERIA 50
#define MAX_ALUMNOS 50
#define MAX_MATERIAS 50
#define MAX_CORRELATIVAS 5
#define MAX_NOMBRE 100
#define TRUE 1
#define FALSE 0

#endif // CONFIG_H